version: "3.4"

networks:
  mysql-network:
    name: mysql-network
    driver: overlay
    external: true    

services:  
  management1:
    image: mysql/mysql-cluster:8.0
    container_name: management1
    env_file: .env.cluster
    restart: always
    build: .
    command: ndb_mgmd
    volumes:
      - ./mysql-config/my.cnf:/etc/my.cnf
      - ./mysql-config/mysql-cluster.cnf:/etc/mysql-cluster.cnf
    networks:
      - mysql-network

  ndb1:
    image: mysql/mysql-cluster:8.0
    container_name: ndb1
    env_file: .env.cluster
    restart: always
    build: .
    command: ndbd
    volumes:
      - ./mysql-config/my.cnf:/etc/my.cnf
      - ./mysql-config/mysql-cluster.cnf:/etc/mysql-cluster.cnf
    networks:
      - mysql-network

  ndb2:
    image: mysql/mysql-cluster:8.0
    container_name: ndb2
    env_file: .env.cluster
    restart: always
    build: .
    command: ndbd
    volumes:
      - ./mysql-config/my.cnf:/etc/my.cnf
      - ./mysql-config/mysql-cluster.cnf:/etc/mysql-cluster.cnf
    networks:
      - mysql-network

  mysql1:
    image: mysql/mysql-cluster:8.0
    container_name: mysql1
    env_file: .env.cluster
    restart: always
    build: .
    command: mysqld --default-authentication-plugin=mysql_native_password
             --init-file /docker-entrypoint-initdb.d/bd_tutorias.sql
             --lower_case_table_names=1
    environment:
      - TZ:${TZ}
      - MYSQL_DATABASE:${MYSQL_DATABASE}
      - MYSQL_USER:${MYSQL_USER}
      - MYSQL_PASSWORD:${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD:${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./mysql-config/my.cnf:/etc/my.cnf
      - ./mysql-config/mysql-cluster.cnf:/etc/mysql-cluster.cnf
      - ./mysql-config/data:/var/lib/mysql
      - ./mysql-dump/bd_tutorias.sql:/docker-entrypoint-initdb.d/bd_tutorias.sql
    networks:
      - mysql-network
    ports:
      - 3306:3306
