version: "3.4"

networks:
  mysql-cluster:
    name: mysql-cluster
    driver: bridge    
    ipam:
      driver: default
      config:
        - subnet: 192.168.0.0/16

x-env-files:  &env-file
  env_file:
    - .env.cluster

services:  
  management1:
    image: mysql/mysql-cluster:8.0
    container_name: management1
    <<: *env-file
    restart: always
    build: .
    command: ndb_mgmd
    volumes:
      - ./mysql/my.cnf:/etc/my.cnf
      - ./mysql/mysql-cluster.cnf:/etc/mysql-cluster.cnf
    networks:
      mysql-cluster:
        ipv4_address: 192.168.0.2

  ndb1:
    image: mysql/mysql-cluster:8.0
    container_name: ndb1
    <<: *env-file
    restart: always
    build: .
    command: ndbd
    volumes:
      - ./mysql/my.cnf:/etc/my.cnf
      - ./mysql/mysql-cluster.cnf:/etc/mysql-cluster.cnf
    networks:
      mysql-cluster:
        ipv4_address: 192.168.0.3

  ndb2:
    image: mysql/mysql-cluster:8.0
    container_name: ndb2
    <<: *env-file
    restart: always
    build: .
    command: ndbd
    volumes:
      - ./mysql/my.cnf:/etc/my.cnf
      - ./mysql/mysql-cluster.cnf:/etc/mysql-cluster.cnf
    networks:
      mysql-cluster:
        ipv4_address: 192.168.0.4

  mysql1:
    image: mysql/mysql-cluster:8.0
    container_name: mysql1
    <<: *env-file
    restart: always
    build: .
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      - TZ:${TZ}
      - MYSQL_DATABASE:${MYSQL_DATABASE}
      - MYSQL_USER:${MYSQL_USER}
      - MYSQL_PASSWORD:${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD:${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./mysql/my.cnf:/etc/my.cnf
      - ./mysql/mysql-cluster.cnf:/etc/mysql-cluster.cnf
      - ./mysql/data:/var/lib/mysql
    networks:
      mysql-cluster:
        ipv4_address: 192.168.0.10
    ports:
      - 3306:3306
